<div style="margin-top: 8px;" class="table">
    <div class="head">
        <h5 class="iFrames">
                    
            <?=$this->item? "Редактирование записи":'Добавление запсии'?>
                     
        </h5>
    </div>
    <form action="/admin/objects/save/id/<?=$this->item['id']?>" class="ajax-form" method="post">
        <table cellspacing="0" cellpadding="0" border="0" class="display edit-table" id="con-edit" >
            <thead>
            <tr>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
                    <div class="DataTables_sort_wrapper">
                        Характеристика
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
                    <div class="DataTables_sort_wrapper">
                        Значение
                    </div>
                </th>
		          
            </tr>
            </thead>
            <tbody>
            <a></a>
        
            <?if($this->item): ?>
      
                <tr>
                    <td>
                        ID
                    </td>
                    <td>
                        <?=htmlspecialchars(strip_tags($this->item['id']))?>
                        <input type="hidden" name="id" value="<?=htmlspecialchars(strip_tags($this->item['id']))?>"/>
                    </td>
                </tr>
        
            <?endif;?>
      
            <tr>
                <td>
                    Страна
                </td>
                <td>
                    <select type="text" name="country" id="objects_country"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->country, $this->item["country"])?></select>
                </td>
            </tr><tr>
                <td>
                    Регион
                </td>
                <td>
                    <select type="text" name="region" id="objects_region"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->region, $this->item["region"])?></select>
                </td>
            </tr><tr>
                <td>
                    Город
                </td>
                <td>
                    <select type="text" name="city" id="objects_city"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->city, $this->item["city"])?></select>
                </td>
            </tr><tr>
                <td>
                    Рынок
                </td>
                <td>
                    <select type="text" name="market" id="objects_market"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->market, $this->item["market"])?></select>
                </td>
            </tr><tr>
                <td>
                    Тип
                </td>
                <td>
                    <select type="text" name="type" id="objects_type"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->type, $this->item["type"])?></select>
                </td>
            </tr><tr>
                <td>
                    Пл.
                </td>
                <td>
                    <input type="text" name="area" id="objects_area" value="<?=strip_tags(htmlspecialchars($this->item["area"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    вся жилая пл.
                </td>
                <td>
                    <input type="text" name="all_sq" id="objects_all_sq" value="<?=strip_tags(htmlspecialchars($this->item["all_sq"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    жилая пл.
                </td>
                <td>
                    <input type="text" name="living_sq" id="objects_living_sq" value="<?=strip_tags(htmlspecialchars($this->item["living_sq"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    пл. кухни
                </td>
                <td>
                    <input type="text" name="kithcen_sq" id="objects_kithcen_sq" value="<?=strip_tags(htmlspecialchars($this->item["kithcen_sq"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    цена
                </td>
                <td>
                    <input type="text" name="price" id="objects_price" value="<?=strip_tags(htmlspecialchars($this->item["price"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    Валюта
                </td>
                <td>
                    <select type="text" name="cur" id="objects_cur"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->cur, $this->item["cur"])?></select>
                </td>
            </tr><tr>
                <td>
                    раст. до моря
                </td>
                <td>
                    <input type="text" name="to_sea" id="objects_to_sea" value="<?=strip_tags(htmlspecialchars($this->item["to_sea"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    раст. до аэроп.
                </td>
                <td>
                    <input type="text" name="to_airport" id="objects_to_airport" value="<?=strip_tags(htmlspecialchars($this->item["to_airport"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    кол. ком.
                </td>
                <td>
                    <input type="text" name="rooms" id="objects_rooms" value="<?=strip_tags(htmlspecialchars($this->item["rooms"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    этаж
                </td>
                <td>
                    <input type="text" name="floor" id="objects_floor" value="<?=strip_tags(htmlspecialchars($this->item["floor"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    кол. этажей
                </td>
                <td>
                    <input type="text" name="all_floors" id="objects_all_floors" value="<?=strip_tags(htmlspecialchars($this->item["all_floors"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    кол. ваных ком.
                </td>
                <td>
                    <input type="text" name="bath_rooms" id="objects_bath_rooms" value="<?=strip_tags(htmlspecialchars($this->item["bath_rooms"]))?>" class="objects-field " />
                </td>
            </tr><tr>
                <td>
                    Состояние
                </td>
                <td>
                    <select type="text" name="state" id="objects_state"  class="objects-field"  >
                        <?=K_jformhelper::options($this->selects->state, $this->item["state"])?></select>
                </td>
            </tr>
            <tr>
                <td>
                    Описание
                </td>
                <td>
                    <textarea id="description" name="description" cols="100" rows="10"><?=$this->item["des"]?></textarea>
                </td>
            </tr>



            </tbody>

        </table>

        <input type="submit" value="<?=$this->item? "Обновить":'Создать'?>" id="add_button" class="b-button greyishBtn submitForm add_node_button"/>
        <div style="display:none" class="nNote hideit" id="flash-msg-nNote">
            <p>
            </p>
        </div>


    </form>

    <div style="padding: 20px;padding-top: 30px;">
        <?if($this->item):?>

            Изображения для объекта:

            <div id="object_images" data-filename="object_images" class="multifile" >

                <div id="object-images-conteiner" >

                    <?

                    foreach($this->objimg as $i):

                        $thumbSrc = '/upload/objects/thumb/'.$i['img'];

                        ?>

                            <div style="margin:15px 0" id="img_<?= $i['id']?>">



                                    <form action="/admin/objects/imageadd" class="image-update" method="POST" enctype="multipart/form-data">

                                        <img src="<?=$thumbSrc?>" class="rounded" width="100"/>

                                        <input style="width:220px" class="object_images" id="object_images_f_0" type="file" name="images_f">

                                        <input type="hidden" name="img_id" value="<?=$i['id']?>">

                                        <input type="hidden" name="id_add" value="<?=$this->item['id_add']?>"><br>

                                        <input type="checkbox" class="first_img" value="Первая картинка" name="first_img" data-idimg="<?=$i['id']?>" data-idadd="<?=$this->item['id_add']?>">

                                        <button class="file_field_update update-image" href="javascript:void(0);" title="Обновить"></button>

                                        <a data-image="<?=$i['id']?>" class="file_field_delete remove-image" href="javascript:void(0);" title="Удалить"></a><br/>
                                    </form>



                            </div>
                        <?

                    endforeach;?>

                </div>

                Добавить ещё картинку
                <div class="add-image-container">

                    <form action="/admin/objects/imageadd" class="add-image"  method="POST" enctype="multipart/form-data">

                        <input style="width:220px" class="object_images" type="file" name="images_f">

                        <input type="hidden" name="id_add" value="<?=$this->item['id_add']?>">

                        <input type="submit" name="image_add" value="Добавить">

                    </form>

                </div>

            </div>
        <?else:?>

            Картинки можно будет добавить после создания объекта.

        <?endif;?>

    </div>
</div>
        
   
        
