<div style="margin-top: 8px;" class="table" id="objects_table_wrapper">
	<div class="head">
		<h5 class="iFrames">
		    <?=$this->crudTitle?>
		</h5>
	</div>
	<div class="dataTables_wrapper" id="objects_crud_wrapper">
        	
			<div class="dataTables_filter" id="acl-users_filter">
                          <a class="drop_filtres" onfocus="this.blur();" title="Сбросить фильтры" href="javascript:;"></a>
                          <span class="srchbutton b-button greyishBtn add_node_button"> Поиск </span>
            </div>
  			
		<table cellspacing="0" cellpadding="0" border="0" class="display">
			<thead>
				<tr>
                     <th class="ui-state-default" rowspan="1" colspan="1" style="width:40px;">
<div class="DataTables_sort_wrapper">ID<br/>
<input type="text" name="id" <?=isset($_GET['id'])? 'value="'.strip_tags(htmlspecialchars($_GET["id"])).'"' : ""?>  id="objects_id" style="width:40px;" class="objects-field" />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Страна<br/>
<select type="text" name="country" id="objects_country" style="width:80px;"  class="objects-field"  >
<?=K_jformhelper::options($this->selects->country, isset($_GET['country'])? strip_tags(htmlspecialchars($_GET["country"])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Регион<br/>
<select type="text" name="category" id="objects_category" style="width:80px;"  class="objects-field"  >
<?=K_jformhelper::options($this->selects->category, isset($_GET['category'])? strip_tags(htmlspecialchars($_GET["category"])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Тип<br/>
<select type="text" name="type" id="objects_type" style="width:80px;"  class="objects-field"  >
<?=K_jformhelper::options($this->selects->type, isset($_GET['type'])? strip_tags(htmlspecialchars($_GET["type"])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:40px;">
<div class="DataTables_sort_wrapper">площадь<br/>
<input type="text" name="area" <?=isset($_GET['area'])? 'value="'.strip_tags(htmlspecialchars($_GET["area"])).'"' : ""?>  id="objects_area" style="width:40px;" class="objects-field" />
</div>
</th>

                     
                    <th class="ui-state-default" rowspan="1" colspan="1" >
    		             <div class="DataTables_sort_wrapper">Управление</div>
                    </th>
            	</tr>
			</thead>
			<tbody>
	       	</tbody>
		</table>
		<div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
			<div id="acl-users_length" class="dataTables_length">
				<label>
					Элементов на страницу:
					<select name="acl-users_length" class="on-page-count" size="1">
						<option value="5">
							5
						</option>
						<option value="10" selected="selected">
							10
						</option>
						<option value="25">
							25
						</option>
						<option value="50">
							50
						</option>
						<option value="100">
							100
						</option>
					</select>
				</label>
			</div>
			<div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="acl-users_paginate">
				<span class="toFirst ui-corner-tl ui-corner-bl fg-button ui-button ui-state-disabled" id="acl-users_first">
					Первая
				</span>
				<span class="previous fg-button ui-button ui-state-disabled" id="acl-users_previous">
					Предыдущая
				</span>
				<span>
					<span class="fg-button ui-button ui-state-disabled">
						1
					</span>
				</span>
				<span class="next fg-button ui-button ui-state-disabled" id="acl-users_next">
					Следующая
				</span>
				<span class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-disabled" id="acl-users_last">
					Последняя
				</span>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

$(function(){
    
   $('#objects_table_wrapper').ajaxLeaf({
    
			loadUrl:'/admin/objects/load',
			itemsContainer: '#objects_crud_wrapper',
            collectInfo:function(wrap){
                
                     var addInfoArray = [];
                
                     wrap.find('.objects-field').each(function(){
                        
                          addInfoArray.push($(this).attr('name')+'='+$(this).val());
                       
                     });
                  
                     addInfo = addInfoArray.join('&');
                         
               	     return addInfo;
                     
			},
                 
            dropFiltres:function(wrap){
                
                     wrap.find('.objects-field').each(function(){
                        
                         if($(this).tagName.toLowerCase()=="select"){
                            
                            $(this).find('options').attr('selected', false);
                          
                         }else{
                            
                            $(this).val('');
                            
                         }
                       
                     });
                      
            },    
                 
            dropFiltresButtonInd: '.drop_filtres',   
            srchButtonInd: '.srchbutton',
   			"renderItems": function(items) {
    				var itemsHtml = [];
    				$.each(items, function(id, v) {
    				itemsHtml.push('<tr class="objects_row" id="objects-row-' + v.id + '" rel="' + v.idname + '" ><td>' + v.id + '</td><td>' + v.country + '</td><td>' + v.category + '</td><td>' + v.type + '</td><td>' + v.area + '</td><td><a href="javascript:void(0);" data-id="' + v.id + ' "class="crud-edit"></a><a title="Удалить запись" href="javascript:void(0);" data-id="' + v.id + '" class="crud-delete"></a></td></tr>');
                    });
                    
    				return itemsHtml;
            }
   }); 

   $('#objects_crud_wrapper').on('click', '.crud-edit', function(){
            
            var id = $(this).data('id');
            
            $.get('/admin/objects/edit','id='+id, function(data){
                  flyboxOpen(900+44,700, 'Управление', '<div style="padding:0 10px;width:900px;height:700px;overflow-x:auto">'+data+'</div>');
            },'html');
                    
   });
     
   $('#objects_crud_wrapper').on('click', '.crud-delete', function(){
            
        var id = $(this).data('id');
          
		
		if (confirm("Вы действительно хотите удалить эту запись?")) {
			
            $.post('/admin/objects/remove',{id:id}, function(data){
                if(data.error){
				
				 	alert(data.msg);			 
				 
				}else{
				
					$('#<%crudName%>-row-'+data.id).remove();
				 
				}
				
            },'json');
        }
		
   });	 
	 
  /*
  $("#tree_title").syncTranslit({
    destination: "tree_name",
    urlSeparator: "-"
  });*/
  
});

</script>