<div class="content">

    <div class="block">
        <div class="p_cont">
            <h1>Карта сайта</h1>
            <script type="text/javascript" src="//yandex.st/share/share.js"
                    charset="utf-8"></script>
            <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug,gplus,surfingbird"></div>

            <span class="intro">Карта сайта</span>
            <div class="clear"></div>

            <p><ul><li><a href="/" title="Главная" >Главная</a></li>
                <li><a href="/altair" title="ЖК Альтаир" >ЖК Альтаир</a></li>
                <li><a href="/gen" title="ЖК Генуэзский" >ЖК Генуэзский</a></li>
                <li><a href="/star2" title="ЖК Звездный 2" >ЖК Звездный 2</a></li>
                <li>
                    <a href="/objects" title="Сданные объекты" >Сданные объекты</a>
                    <ul>
                        <?php foreach ($this->obj as $v) { ?>
                        <li><a href="<?= $v['tree_name']?>" title="<?= $v['name_build']?>" ><?= $v['name_build']?></a></li>
                        <? } ?>
                    </ul>
                </li>
                <li class="last active"><a href="/map" title="Карта сайта" >Карта сайта</a></li>
            </ul></p>
        </div>
    </div>
    <div class="kran_cont"></div>
</div>