<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Админка</title>

<link href="/adm/css/main.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css' />

<script src="/adm/js/jquery-1.7.2.min.js" type="text/javascript"></script>

<script type="text/javascript" src="/adm/js/spinner/jquery.mousewheel.js"></script>
<script type="text/javascript" src="/adm/js/spinner/ui.spinner.js"></script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script> 

<script type="text/javascript" src="/adm/js/fileManager/elfinder.min.js"></script>

<script type="text/javascript" src="/adm/js/wysiwyg/jquery.wysiwyg.js"></script>
<script type="text/javascript" src="/adm/js/wysiwyg/wysiwyg.image.js"></script>
<script type="text/javascript" src="/adm/js/wysiwyg/wysiwyg.link.js"></script>
<script type="text/javascript" src="/adm/js/wysiwyg/wysiwyg.table.js"></script>

<script type="text/javascript" src="/adm/js/dataTables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/adm/js/dataTables/colResizable.min.js"></script>

<script type="text/javascript" src="/adm/js/forms/forms.js"></script>
<script type="text/javascript" src="/adm/js/forms/autogrowtextarea.js"></script>
<script type="text/javascript" src="/adm/js/forms/autotab.js"></script>
<script type="text/javascript" src="/adm/js/forms/jquery.validationEngine-en.js"></script>
<script type="text/javascript" src="/adm/js/forms/jquery.validationEngine.js"></script>

<script type="text/javascript" src="/adm/js/colorPicker/colorpicker.js"></script>

<script type="text/javascript" src="/adm/js/uploader/plupload.js"></script>
<script type="text/javascript" src="/adm/js/uploader/plupload.html5.js"></script>
<script type="text/javascript" src="/adm/js/uploader/plupload.html4.js"></script>
<script type="text/javascript" src="/adm/js/uploader/jquery.plupload.queue.js"></script>

<script type="text/javascript" src="/adm/js/ui/progress.js"></script>
<script type="text/javascript" src="/adm/js/ui/jquery.jgrowl.js"></script>
<script type="text/javascript" src="/adm/js/ui/jquery.tipsy.js"></script>
<script type="text/javascript" src="/adm/js/ui/jquery.alerts.js"></script>

<script type="text/javascript" src="/adm/js/jBreadCrumb.1.1.js"></script>
<script type="text/javascript" src="/adm/js/cal.min.js"></script>
<script type="text/javascript" src="/adm/js/jquery.collapsible.min.js"></script>
<script type="text/javascript" src="/adm/js/jquery.ToTop.js"></script>
<script type="text/javascript" src="/adm/js/jquery.listnav.js"></script>
<script type="text/javascript" src="/adm/js/jquery.sourcerer.js"></script>

<script type="text/javascript" src="/adm/js/jquery.form.js"></script>

<script type="text/javascript" src="/adm/js/tree/tree.jquery.js"></script>
<script type="text/javascript" src="/adm/js/jquery.cookie.js"></script>
<link href="/adm/js/tree/jqtree.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/adm/js/custom.js"></script>
<script type="text/javascript" src="/adm/js/main.js"></script>

<script src="/adm/js/jquery.formbuilder.js"></script>
<link rel="stylesheet" media="screen" href="/adm/css/jquery.formbuilder.css"/>
		
</head>

<body>

<!-- Top navigation bar -->
<div id="topNav">
    <div class="fixed">
        <div class="wrapper">
            <div class="welcome"><span>Добро пожаловать в панель управления сайтом!</span></div>
            <div class="userNav">
                <ul>
                    <li><a href="#" title=""><img src="/adm/img/icons/topnav/settings.png" alt="" /><span>Настройки</span></a></li>
                    <li><a href="login.html" title=""><img src="/adm/img/icons/topnav/logout.png" alt="" /><span>Выйти</span></a></li>
                </ul>
            </div>
            <div class="fix"></div>
        </div>
    </div>
</div>

<!-- Header -->
<div id="header" class="wrapper">
    <div class="middleNav">
    	<ul>
        	<li class="iSite"><a href="/" title=""><span>Перейти на сайт</span></a></li>
            <li class="iReload"><a href="javascript:window.location.reload();" title=""><span>Перезагрузить</span></a></li>
        </ul>
    </div>
    <div class="fix"></div>
</div>


<!-- Content wrapper -->
<div class="wrapper">
	
	<?php if (isset($this->ajaxed) && $this->ajaxed === true) { ?>
		<!-- Left navigation -->
		<div class="leftNav">
			<div class="b-tree" id="tree">
			</div>
			<div class="b-new-type">
				<a href="/admin/types/add">Добавить новый тип</a>
			</div>
		</div>
		
		<!-- Content -->
		<div class="content">
			<div class="widget tabsRight b-main-tabs">
				<div class="head"><h5 class="iFrames">Управление сайтом</h5></div>       
				<ul class="tabs" id="ajax_load_place_tabs">
					<li><a href="#tab1">Главная</a></li>
				</ul>
				
				<div class="tab_container" id="ajax_load_place_tab_container">
					<div id="tab1" class="tab_content">
						Добро пожаловать в систему управления сайтом!
					</div>
				</div>	
				<div class="fix"></div>	 
			</div>
		</div>
	<?php } else {  ?>	
		<div class="widget tabsRight b-main-tabs">
			<div class="head"><h5 class="iFrames">Управление сайтом</h5></div>       
			<ul class="tabs" id="ajax_load_place_tabs">				
				<li><a href="#tab1"><?=$this->header?></a></li>
				<li><a href="/admin/" title="Вернуться обратно">вернуться</a></li>
			</ul>
			
			<div class="tab_container" id="ajax_load_place_tab_container">
				<div id="tab1" class="tab_content">
					<?=$this->context()?>
				</div>
			</div>	
			<div class="fix"></div>	 
		</div>
	<?php } ?>
	
    <div class="fix"></div>
</div>

<!-- Footer -->
<div id="footer">
	<div class="wrapper">
    </div>
</div>

</body>
</html>