<a class="btnIconLeft mr10 mt5 mb10 flr"  onclick="addModel()" href="javascript:void(0)">
<img class="icon" src="/adm/img/icons/dark/add.png" alt="Новая модель"/>
<span>Новая модель</span>
</a>

<a class="btnIconLeft mr10 mt5 mb10 flr"  onclick="addController()" href="javascript:void(0)">
<img class="icon" src="/adm/img/icons/dark/add.png" alt="Новый контроллер"/>
<span>Новый контроллер</span>
</a>

<a class="btnIconLeft mr10 mt5 mb10 flr"  onclick="addHMVCblock()" href="javascript:void(0)">
<img class="icon" src="/adm/img/icons/dark/add.png" alt="Новый HMVC блок"/>
<span>Новый HMVC блок</span>
</a>

<div class="fix"></div>

