<div style="display:none" class="nNote hideit" id="flash-msg-nNote">
	<p>
	</p>
</div>
<div style="margin-top: 8px;" class="table">

            	<div class="head">
            		<h5 class="iFrames">
                        Добавление нового HMVC блока
            		</h5>
            	</div>
                
<form action="/dev/addhmvcblock/save" class="ajax-form" method="post">                
    <table cellspacing="0" cellpadding="0" border="0" class="display edit-table" id="con-edit" >
                <thead>
    				<tr>
                    
                   		<th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
    						<div class="DataTables_sort_wrapper">
    					    	Характеристика
    						</div>
    					</th>
                        
    					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
    						<div class="DataTables_sort_wrapper">
    				    		Значение
    						</div>
    					</th>
    		          
          			</tr>
    		 	</thead>
      	<tbody>
           	<tr>
    			<td>
    		     Заголовок нового HMVC блока
    			</td>
    			<td>
    				<input type="text" name="title"/>
    			</td>
    		</tr>
			<tr>
    			<td>
    		     Название нового HMVC блока
    			</td>
    			<td>
    				<input type="text" name="name"/>
    			</td>
    		</tr>
       	</tbody>  
    </table>
    <br/>
    <br/>
    
    <input type="submit" value="Добавить" id="add_button" class="b-button greyishBtn submitForm add_node_button"/>
</form>
</div>
        
        
        
