<div style="margin-top: 8px;" class="table">
            	<div class="head">
            		<h5 class="iFrames">
                    
                     <?=$this->item? "Редактирование записи":'Добавление запсии'?>
                     
            		</h5>
            	</div>
<form action="/admin/jk/save/id/<?=$this->item['id']?>" class="ajax-form" method="post">                
<table cellspacing="0" cellpadding="0" border="0" class="display edit-table" id="con-edit" >
            <thead>
				<tr>
               		<th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
						<div class="DataTables_sort_wrapper">
					    Характеристика
						</div>
					</th>
					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
						<div class="DataTables_sort_wrapper">
						Значение
						</div>
					</th>
		          
      			</tr>
		 	</thead>
  	<tbody>
      <a></a>
        
      <?if($this->item): ?>
      
		<tr>
			<td>
			ID
			</td>
			<td>
		       <?=htmlspecialchars(strip_tags($this->item['id']))?>
               <input type="hidden" name="id" value="<?=htmlspecialchars(strip_tags($this->item['id']))?>"/>
			</td>
		</tr>
        
      <?endif;?>
      
      <tr>
                                            			<td>
                                            	           	Дата добавления
                                            			</td>
                                            			<td>
<input type="text" name="date" id="jk_date" value="<?=strip_tags(htmlspecialchars($this->item["date"]))?>" class="jk-field datepicker" />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Пользователь
                                            			</td>
                                            			<td>
<select type="text" name="user" id="jk_user"  class="jk-field"  >
<?=K_jformhelper::options($this->selects->user, $this->item["user"])?></select>
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Область
                                            			</td>
                                            			<td>
<select type="text" name="region" id="jk_region"  class="jk-field"  >
<?=K_jformhelper::options($this->selects->region, $this->item["region"])?></select>
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Наз. жк
                                            			</td>
                                            			<td>
<input type="text" name="jk_name" id="jk_jk_name" value="<?=strip_tags(htmlspecialchars($this->item["jk_name"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Фото жк
                                            			</td>
                                            			<td>
<input type="text" name="img" id="jk_img" value="<?=strip_tags(htmlspecialchars($this->item["img"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Наз. компании
                                            			</td>
                                            			<td>
<input type="text" name="company_name" id="jk_company_name" value="<?=strip_tags(htmlspecialchars($this->item["company_name"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Лого компании
                                            			</td>
                                            			<td>
<input type="text" name="company_logo" id="jk_company_logo" value="<?=strip_tags(htmlspecialchars($this->item["company_logo"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Утв..
                                            			</td>
                                            			<td>
<input type="text" name="moderation" id="jk_moderation" value="<?=strip_tags(htmlspecialchars($this->item["moderation"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Сайт
                                            			</td>
                                            			<td>
<input type="text" name="site" id="jk_site" value="<?=strip_tags(htmlspecialchars($this->item["site"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Текст
                                            			</td>
                                            			<td>
<textarea name="text" rows="10" cols="50" id="jk_text" class="jk-field"><?=strip_tags(htmlspecialchars($this->item["text"]))?></textarea></td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Адрес
                                            			</td>
                                            			<td>
<input type="text" name="street" id="jk_street" value="<?=strip_tags(htmlspecialchars($this->item["street"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Номер дома
                                            			</td>
                                            			<td>
<input type="text" name="house" id="jk_house" value="<?=strip_tags(htmlspecialchars($this->item["house"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Количество секций
                                            			</td>
                                            			<td>
<input type="text" name="sec_num" id="jk_sec_num" value="<?=strip_tags(htmlspecialchars($this->item["sec_num"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Количество секций
                                            			</td>
                                            			<td>
<input type="text" name="sec_level" id="jk_sec_level" value="<?=strip_tags(htmlspecialchars($this->item["sec_level"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Количество квартир
                                            			</td>
                                            			<td>
<input type="text" name="flat_num" id="jk_flat_num" value="<?=strip_tags(htmlspecialchars($this->item["flat_num"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Количество квартир
                                            			</td>
                                            			<td>
<input type="text" name="parking" id="jk_parking" value="<?=strip_tags(htmlspecialchars($this->item["parking"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Материал
                                            			</td>
                                            			<td>
<input type="text" name="material" id="jk_material" value="<?=strip_tags(htmlspecialchars($this->item["material"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Код телефона
                                            			</td>
                                            			<td>
<input type="text" name="code" id="jk_code" value="<?=strip_tags(htmlspecialchars($this->item["code"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Телефон
                                            			</td>
                                            			<td>
<input type="text" name="phone" id="jk_phone" value="<?=strip_tags(htmlspecialchars($this->item["phone"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Электронная почта
                                            			</td>
                                            			<td>
<input type="text" name="email" id="jk_email" value="<?=strip_tags(htmlspecialchars($this->item["email"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Дата начала строительства
                                            			</td>
                                            			<td>
<input type="text" name="start_date" id="jk_start_date" value="<?=strip_tags(htmlspecialchars($this->item["start_date"]))?>" class="jk-field datepicker" />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Дата сдачи
                                            			</td>
                                            			<td>
<input type="text" name="finish_date" id="jk_finish_date" value="<?=strip_tags(htmlspecialchars($this->item["finish_date"]))?>" class="jk-field datepicker" />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Цена от
                                            			</td>
                                            			<td>
<input type="text" name="price_from" id="jk_price_from" value="<?=strip_tags(htmlspecialchars($this->item["price_from"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Цена до
                                            			</td>
                                            			<td>
<input type="text" name="price_to" id="jk_price_to" value="<?=strip_tags(htmlspecialchars($this->item["price_to"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Видео на youtube
                                            			</td>
                                            			<td>
<input type="text" name="video_link" id="jk_video_link" value="<?=strip_tags(htmlspecialchars($this->item["video_link"]))?>" class="jk-field " />
</td>
                                                		</tr><tr>
                                            			<td>
                                            	           	Объект сдан?
                                            			</td>
                                            			<td>
<input type="text" name="is_complete" id="jk_is_complete" value="<?=strip_tags(htmlspecialchars($this->item["is_complete"]))?>" class="jk-field " />
</td>
                                                		</tr>      
    
             
</tbody>

</table>

<input type="submit" value="<?=$this->item? "Обновить":'Создать'?>" id="add_button" class="b-button greyishBtn submitForm add_node_button"/>
<div style="display:none" class="nNote hideit" id="flash-msg-nNote">
	<p>
	</p>
</div>
</form>

</div>
        
   
        
