<div class="b-padded mainForm wideForm">
<div id="flash-msg-nNote"  class="nNote hideit" style="display:none">
   <p></p>
</div>  
  	<?=$this->generateClientForm('/client_forms/feedback/','/admin/clientformtest/save');//$this->generateForm($this->formStructure['form_structure'], (isset($this->type) ? $this->type : array()), array('/admin/types/'.($this->actionType == 'create' ? $this->actionType : $this->actionType.'/id/'.$this->type['type_id']), 'post', $this->actionType, 'multipart/form-data'), $this->formTemplate)?>
</div>