<div class="obj-list">
    <div class="one-obj">

        <div class="images">
            <?php
            $imgs = explode(',', $this->novostroy['imgs']);
            foreach ($imgs as $im){ ?>
                <img src="/upload/<?= $im ?>" width="100" height="100">
                <br>
            <?php } ?>
        </div>

        <div class="title">ID: <?= $this->novostroy['id'] ?></div>
        <div class="country">
            Страна: <?= $this->novostroy['country'] ?>/<?= $this->novostroy['region'] ?>/<?= $this->novostroy['city'] ?>
        </div>
        <div>Комнат: <?= $this->novostroy['rooms'] ?></div>
        <div>Площадь: <?= $this->novostroy['all_sq'] ?></div>
        <div>Жилая: <?= $this->novostroy['living_sq'] ?></div>
        <div>Кухня: <?= $this->novostroy['kithcen_sq'] ?></div>
        <div>Этаж: <?= $this->novostroy['floor'] ?></div>
        <div>Этажность: <?= $this->novostroy['all_floors'] ?></div>
        <div>Описание: <?= $this->novostroy['des'] ?></div>

        <button type="button" data-id="<?= $this->novostroy['id'] ?>" class="favorit-btn favorit-btn-add fav-btn">В избраное</button>

        <div class="intro"><?= $this->novostroy['fullText'] ?></div>

    </div>
</div>