    <div class="question">
        <p>Есть Вопрос?</p>
        <button class="show-form">ОНЛАЙН ЗАЯВКА</button>
    </div>
    <div class="form">
        <div id="forma">
            <h1>Ждем Ваших писем</h1>
            <span class="valid"></span>
            <br>
            <form class="ajax-form" method="post" id="form1" name="myform" action="/ajax/forms/contactus">
                <input type="hidden" name="form1" value="form1">
                <table cellpadding="0" cellspacing="0">
                    <tbody><tr>
                        <td class="label">Имя:</td>
                        <td><input class="in-field" type="text" name="name" maxlength="60" value=""><br><br></td>
                    </tr>
                    <tr>
                        <td class="label">Ваш телефон:</td>
                        <td><input class="in-field" type="text" name="phone" maxlength="40" value=""><br><br></td>
                    </tr>
                    <tr>
                        <td class="label">E-mail:</td>
                        <td><input class="in-field" type="text" name="email" maxlength="40" value=""><br><br></td>
                    </tr>
                    <tr>
                        <td class="label">Текст письма:</td>
                        <td><textarea name="mess"></textarea><br><br></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input class="btn-sub" type="submit" name="submit" value="Отправить"></td>
                    </tr>
                    </tbody></table>

                <input type="hidden" name="formid" value="form1"></form>
        </div>
        <div id="flash-msg-note" style="display: none;"></div>
    </div>

    <div id="mi-slider" class="mi-slider">
        <?php
        $first = array_shift($this->slider);
        foreach($first['tree_childs'] as $country) { ?>
            <ul>
                <?php foreach($country['tree_childs'] as $v) { ?>
                    <li>
                        <a href="<?= $v['tree_name'] ?>">
                            <img src="/upload/<?= $v['image']?>">
                            <h4><?= $v['name_build'] ?></h4>
                        </a>
                    </li>
                <?php }?>
            </ul>
        <?php } ?>

        <nav>
            <?php foreach($first['tree_childs'] as $country) { ?>
                <a href="#"><?= $country['tree_title'] ?></a>
            <?}?>
        </nav>

        <div class="slider-head"></div>
        <div class="slider-head-img"></div>
    </div>

    <div id="mi-slider2" class="mi-slider">
        <?php
        $first = array_shift($this->slider2);
        foreach($first['tree_childs'] as $country) { ?>
            <ul>
                <?php foreach($country['tree_childs'] as $v) { ?>
                    <li>
                        <a href="<?= $v['tree_name'] ?>">
                            <img src="/upload/<?= $v['image']?>">
                            <h4><?= $v['name_build'] ?></h4>
                        </a>
                    </li>
                <?php }?>
            </ul>
        <?php } ?>

        <nav>
            <?php foreach($first['tree_childs'] as $country) { ?>
                <a href="#"><?= $country['tree_title'] ?></a>
            <?}?>
        </nav>

        <div class="slider-head"></div>
        <div class="slider-head-img"></div>
    </div>

    <!--Конец main-part-->
</div>
<div class="clear"></div>