    <div id="mi-slider" class="mi-slider">
        <?php foreach($this->menu1 as $m) { ?>
            <ul>
                <?php foreach($this->slider as $s) {
                    if ($s['id'] == $m['idelem1']
                        || $s['id'] == $m['idelem2']
                        || $s['id'] == $m['idelem3']) {?>
                    <li>
                        <a href="/object-<?= $s['id'] ?>">
                            <img src="/upload/<?= $s['first_img']?>">
                            <h4><?= $s['city'] ?></h4>
                        </a>
                    </li>
                <?php }}?>
            </ul>
        <?php } ?>

        <nav>
            <?php foreach($this->menu1 as $m) { ?>
                <a href="#"><?= $m['tree_title'] ?></a>
            <?}?>
        </nav>

        <div class="slider-head"></div>
        <div class="slider-head-img">эксклюзивная продажа</div>
    </div>

    <div id="mi-slider2" class="mi-slider">
        <?php foreach($this->menu2 as $m) { ?>
            <ul>
                <?php foreach($this->slider2 as $s) {
                    if ($s['id'] == $m['idelem1']
                        || $s['id'] == $m['idelem2']
                        || $s['id'] == $m['idelem3']) {?>
                        <li>
                            <a href="/object-<?= $s['id'] ?>">
                                <img src="/upload/<?= $s['first_img']?>">
                                <h4><?= $s['city'] ?></h4>
                            </a>
                        </li>
                    <?php }}?>
            </ul>
        <?php } ?>

        <nav>
            <?php foreach($this->menu2 as $m) { ?>
                <a href="#"><?= $m['tree_title'] ?></a>
            <?}?>
        </nav>

        <div class="slider-head"></div>
        <div class="slider-head-img">новые поступления</div>
    </div>

    <!--Конец main-part-->
</div>
<div class="clear"></div>