<div class="content">
    <div class="p_cont">
        <h2>ЖК Академгородок</h2>
    </div>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="color: #000000;"><img style="float: left; margin-left: 10px; margin-right: 10px;" src="/upload/akadem1.jpg" alt="Новостройка ЖК Академгородок Одесса" width="400" height="300"><span id="internal-source-marker_0.03944814426004595" style="font-size: 90%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif; color: #ffffff;"><a title="ЖК Академгородок" href="http://novidom.od.ua/">ЖК Академгородок</a> это малоэтажный,
                ограждённый, охраняемый жилой комплекс расположенный в Приморском
                районе г. Одессы. </span></span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span id="internal-source-marker_0.03944814426004595" style="font-size: 90%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif; color: #ffffff;">Малоэтажность домов, а также автономное отопление
            обусловленное, наличием 2-х контурных котлов в каждой квартире, выгодно
            отличает комплекс от домов строящихся в Приморском районе. </span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="color: #ffffff;">Престижность
            района, отличная транспортная развязка, хорошо развитая инфраструктура, а
            также наличие мест для культурного, семейного отдыха, превращают
            ЖК Академгородок в комфортабельный и уютный комплекс для жизни.</span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;">&nbsp;</p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;">&nbsp;</p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;">&nbsp;</p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;">&nbsp;</p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;">&nbsp;</p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="font-size: 120%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif; color: #ffffff;">План картинга:&nbsp;</span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="font-size: 120%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif; color: #ffffff;"><img src="/upload/9(1).jpg" alt="паркинг новострой академгородок" width="745" height="371">&nbsp;</span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="font-size: 120%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif; color: #ffffff;">Планировки:</span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="color: #ffffff;"><img src="/upload/academ_pic_2.jpg" alt="квартира академгородок" width="745" height="404"><span style="font-size: 120%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif;">&nbsp;</span></span></p>
    <p style="font-family: Arial,Helvetica,sans-serif; font-size: 16px;"><span style="color: #ffffff;"><img src="/upload/academ_pic_3.jpg" alt="одно двухкомнатные квартиры Одесса" width="744" height="426"><span style="font-size: 120%; font-family: &quot;arial&quot;, &quot;helvetica&quot;, sans-serif;">&nbsp;</span></span></p>
</div>
<div class="clear"></div>