<div id="content-full">
	<div class="product-block">
	<h2><a href="sobstvennoe-proizvodstvo/"><?= t('СОБСТВЕННОЕ ПРОИЗВОДСТВО','OWN PRODUCTION')?></a></h2>

	<hr>
	<?if(count($this->products)>0){?>
	<div id="products">
		<div id="left">	
			<div class="dp">
			<div class="product-line">
				<div class="product-line-center">
				<?
				$i=1;
				foreach($this->products as $product){?>
					
					<div class="product">
							<div>
								<div class="image"><div class="img"><img src="/upload/<?=$product['img']?>" alt="Image"></div></div>
								<div class="name-block">
									<div class="name"><h3><?=$product['longtitle'].' '.$product['name']?></h3></div>
									<div class="angle"></div>
									<div class="shadow"></div>
								</div>
							</div>
					
							<div class="link"><a href="<?=l().$product['tree_link_sub']?>" class="more-link"><?= t('Узнать больше»','More»')?></a></div>
						
					</div>
					<?
						if($i%3==0){?>
						<div style="cler:both"></div>
						</div></div>
						<div class="product-line">
						<div class="product-line-center">
					<?	}
						$i++;
					?>
				<?}?><div style="cler:both"></div>
				</div></div>
			</div>
		</div>
	</div>	
	<?}?>


	</div>
</div>