<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Авторизация</title>

<link href="/adm/css/main.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css' />

<script src="/adm/js/jquery-1.7.2.min.js" type="text/javascript"></script>

<link href="/adm/js/tree/jqtree.css" rel="stylesheet" type="text/css" />
<script src="/adm/js/misc.js" type="text/javascript"></script>

</head>

<body>
<div class="auth-wrapper">


		<div class="widget tabsRight b-main-tabs">
			<div class="head"><h5 class="iFrames">Авторизация</h5></div>       
			
				<div class="tab_content" id="tab1" style="display: block;">
		          <?=$this->context()?>
				</div>

			<div class="fix"></div>	 
		</div>
		
    <div class="fix"></div>
</div>
</body>
</html>






