<div class="content">
        <div class="form">
            <div id="forma">
                <h1>Ждем Ваших писем</h1>
                <span class="valid"></span>
                <br>
                <form class="ajax-form" method="post" id="form1" name="myform" action="/ajax/forms/contactus">
                    <input type="hidden" name="form1" value="form1">
                    <table cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td>Имя:</td>
                            <td><input type="text" name="name" maxlength="60" value=""><br><br></td>
                        </tr>
                        <tr>
                            <td>Фамилия:</td>
                            <td><input type="text" name="lname" maxlength="60" value=""><br><br></td>
                        </tr>
                        <tr>
                            <td>Ваш телефон:</td>
                            <td><input type="text" name="phone" maxlength="40" value=""><br><br></td>
                        </tr>
                        <tr>
                            <td>E-mail:</td>
                            <td><input type="text" name="email" maxlength="40" value=""><br><br></td>
                        </tr>
                        <tr>
                            <td>Текст письма:</td>
                            <td><textarea name="mess"></textarea></td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="submit" name="submit" value="Отправить"></td>
                        </tr>
                        </tbody></table>

                    <input type="hidden" name="formid" value="form1"></form>
            </div>
            <div id="flash-msg-note" style="display: none;"></div>
        </div>
    <div class="kran_cont"></div>
</div>


