<div class="country-block">
    <button class="clear-fav fav-btn">Очистить список</button>
    <div class="clear"></div>

    <div class="obj-list">
        <?php foreach ($this->fav as $v) { ?>
            <div class="obj-item">

                <div class="item-photo">
                    <a href="/object-<?= $v['id'] ?>">
                        <img src="/upload/<?= $v['first_img'] ?>" width="100" height="100">
                    </a>
                </div>

                <div class="item-info">
                    <div class="item-name"><?= $v[''] ?></div>

                    <div class="item-position">
                        <?= $v['country'] ?> / <?= $v['region']; ?> <br> <?= $v['city'] ?>
                    </div>

                    <div class="item-area">
                        Общая площадь: <span><?= $v['area']; ?> м²</span>
                    </div>

                    <div class="item-price">
                        Цена: <span><?= $v['price'] ?> <?= $v['cur'] ?></span>
                    </div>

                    <a href="/object-<?= $v['id'] ?>" class="detal"><u>Подробнее...</u></a>
                    <div class="fix"></div>
                    <button type="button" data-id="<?= $v['id'] ?>" class="favorit-btn favorit-btn-add fav-btn">В избраное</button>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="clear"></div>

    <?
    $cleanUrl = preg_replace('/[\?\&]page=\d*/si', '', $_SERVER['REQUEST_URI']);

    echo K_paginator::simple($this -> page, $this -> pages, $cleanUrl . (strpos($cleanUrl, '?') === false ? '?' : '&') . 'page={#}');
    ?>
</div>