<div class="top-wrapper">
   
            <div class="b-name">
            	<div class="name-page">
                	<h1>Карта сайта</h1>
                </div>
               <?=K_Crumbs::Render()?>    
            </div>
        </div>
        
        <div class="cl"></div> 
        
        <div class="content-all-wrapper">
                
           <div class="sitemap-content">
          
            <?=$this->sitemap?>
         
             
           </div>         
   		
		</div>

        <div class="cl"></div> 