<div class="content">

    <div class="block">
        <div class="p_cont">
            <h1>ЖК Звездный 2</h1>
            <script type="text/javascript" src="//yandex.st/share/share.js"
                    charset="utf-8"></script>
            <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug,gplus,surfingbird"></div>

            <span class="intro"></span>
            <div class="clear"></div>

            <h1><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><em style="font-size: 12px; line-height: 1.5;">Адрес:</em><span style="line-height: 1.5;"> </span><strong style="font-size: 12px; line-height: 1.5;">ул. Маршала Говорова,10</strong></strong></span></h1>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><em>Телефон: </em>(048) 704-91-34</strong></span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><img style="float: left;" src="/upload/opis6_opiss.jpg" alt="Новострой Одесса ЖК Звёздный" width="400" height="386" /></strong></span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">ОБЩАЯ
                    ХАРАКТЕРИСТИКА КОМПЛЕКСА</span><br /><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">
                    <a href="sitemap">ЖК Звездный городок</a> расположен
                    в Приморском районе с развитой инфраструктурой, отвечает самым современным
                    требованиям к качеству жизни.</span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Близость
                    морского побережья с чарующей красотой Черного моря, знаменитыми&nbsp; песчаными пляжами, оборудованными набережными
                    и прекрасным парком Победы &ndash; так выглядит идеальное место для тех, кто мечтает
                    жить на побережьи, при этом находится в центре жизни.</span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Комплекс
                    состоит из 3-х секций переменной этажности, 23 этажа, подземным и наземным
                    паркингом на 270 машиномест.</span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Дома
                    строятся по современным инженерным решениям с использованием
                    монолитно-каркасной технологии.</span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Стены
                    заполнены пенобетоном, современным материалом, который по своим характеристикам
                    превосходит все ранее известные. </span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Отделка
                    фасада из современных отделочных материалов, которые позволяют сохранять тепло
                    зимой и прохладу летом. А также надежно защищает дом от внешних воздействий. </span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Для
                    Вашего удобства предусмотрено 2 лифта &laquo;OTIS&raquo; грузовой и пассажирский. </span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Просторные
                    метражи квартир позволят воплотить Ваши самые смелые дизайнерские решения.
                    Внутренняя отделка квартир соответствует высоким&nbsp; требованиям наших клиентов.</span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">На
                    первых этажах <a href="sitemap">ЖК Звездный 2</a>&nbsp;для комфортного проживания жильцов будут расположены
                    культурно-бытовые объекты, кабинет семейного доктора.</span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 100%;">Многолетний
                    опыт строительной компании &laquo;<a>Будова</a>&raquo; на рынке Одессы, выполнение обязательств
                    перед своими заказчиками позволит Вам не переживать за Ваши инвестиции. </span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><img style="vertical-align: middle;" src="/upload/Planirivki/1kom(1).jpg" alt="" width="381" height="336" />&nbsp; &nbsp; <strong>&nbsp;<span style="color: #000000;">1-комнатные квартиры</span></strong><span style="color: #888888; line-height: 1.5;">&nbsp;</span></span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><img style="vertical-align: middle;" dir="ltr" src="/upload/Planirivki/2kom(2).jpg" alt="" width="400" height="247" /><strong>2-комнатные квартиры</strong></span></p>
            <p><span style="color: #888888; font-family: arial, helvetica, sans-serif; font-size: 120%;"><img style="vertical-align: middle;" src="/upload/Planirivki/3kom(1).jpg" alt="" width="389" height="336" /><strong style="line-height: 1.5; color: #333333;">3-комнатные квартиры</strong></span></p>
            <p>&nbsp;</p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong>Срок сдачи 4 квартал 2013 года</strong></span></p>
            <p><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><br /></strong></span></p>
            <h1 style="text-align: center;"><span style="font-size: 120%; color: #000000; font-family: arial, helvetica, sans-serif;"><strong>Цена от 9000 грн/кв.м</strong></span></h1>
            <p style="text-align: center;"><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><span style="color: #ff0000;"><br /></span></strong></span></p>
            <p class="justifyleft"><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><span style="line-height: 1.5; color: #003300;">Индивидуальные условия рассрочки в зависимости от Вашей ситуации. Гибкий график проплат.&nbsp;</span></strong></span></p>
            <h1 style="text-align: center;"><span style="font-size: 120%; color: #000000; font-family: arial, helvetica, sans-serif;"><strong><span style="line-height: 1.5;">В продаже имеются аппартаменты.</span></strong></span></h1>
            <h1 style="text-align: center;"><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><span style="color: #003300;"><strong><span style="line-height: 1.5; text-align: center;">&nbsp;</span></strong></span><strong style="color: #003300; font-size: 1.5em; line-height: 1.5;"><span style="line-height: 1.5; text-align: center;">&nbsp; 1-комнатные от 44 кв.м</span></strong></span></h1>
            <h1 style="text-align: center;"><span style="color: #003300; font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><span style="line-height: 1.5;"><span style="white-space: pre;">&nbsp;   </span>2-комнатные от 71 кв.м</span></strong></span></h1>
            <h1 style="text-align: center;"><span style="color: #003300; font-family: arial, helvetica, sans-serif; font-size: 120%;"><strong><span style="line-height: 1.5;">&nbsp; &nbsp; &nbsp;3-комнатные &nbsp;от 91 кв.м</span></strong></span></h1>
            <p>&nbsp;</p>
            <h1 style="text-align: center;"><span style="font-size: 120%; color: #000000; font-family: arial, helvetica, sans-serif;"><strong><span style="line-height: 1.5;">Цена от 7500 грн/кв.м</span></strong></span></h1>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h1><span style="font-family: arial, helvetica, sans-serif; font-size: 120%;"><span style="color: #ff0000;"><strong><em>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</em></strong></span><span style="text-align: center; line-height: 1.5;">+38 048 704 91 34</span></span></h1>
        </div>
    </div>
    <div class="kran_cont"></div>
</div>