<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title><?php echo K_SEO::$title ? K_SEO::$title : $meta_t; ?><?=K_Seo::pagePref()?></title>
    <meta name="title" content="<?php echo K_SEO::$title ? K_SEO::$title : $meta_t; ?>" />
    <meta name="keywords" content="<?php echo  K_SEO::$keywords ? K_SEO::$keywords : $meta_k; ?>" />
    <meta name="description" content="<?php echo  K_SEO::$description ? K_SEO::$description : $meta_d; ?><?=K_Seo::pagePref()?>" />
    <link rel="icon" type="image/png" href="/upload/<?= $this->settings['favicon']?>" />
    <?php

    if(K_SEO::$canonical){
	
        echo '<link rel="canonical" href="'.K_SEO::$canonical.'" />';
		
    }

    echo K_SEO::getNext();
    echo K_SEO::getPrev();
    ?>

    <link rel="stylesheet" href="/usr/css/style.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/usr/css/styles.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/usr/css/sprite.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/usr/css/responsive.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/usr/css/slider.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/usr/css/slider-doc.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/usr/css/map.css" type="text/css" media="screen">

    <script type="text/javascript" src="/usr/js/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/usr/js/jquery-migrate-1.2.1.min.js"></script>

    <script src="/usr/js/modernizr.custom.63321.js"></script>
</head>
<body>
<!-- Задний прозрачный фон-->
<div onclick="show('none')" id="wrap"></div>

<!-- Само окно-->
<div id="window">
    <!-- Картинка крестика-->
    <div class="close" onclick="show('none')"></div>

    <div class="form">
        <div id="forma">
            <h1>Ждем Ваших писем</h1>
            <span class="valid"></span>
            <br>
            <form class="ajax-form" method="post" id="form1" name="myform" action="/ajax/forms/contactus">
                <input type="hidden" name="form1" value="form1">
                <table cellpadding="0" cellspacing="0">
                    <tbody><tr>
                        <td class="label">Имя:</td>
                        <td><input class="in-field" type="text" name="name" maxlength="60" value=""><br><br></td>
                    </tr>
                    <tr>
                        <td class="label">Ваш телефон:</td>
                        <td><input class="in-field" type="text" name="phone" maxlength="40" value=""><br><br></td>
                    </tr>
                    <tr>
                        <td class="label">E-mail:</td>
                        <td><input class="in-field" type="text" name="email" maxlength="40" value=""><br><br></td>
                    </tr>
                    <tr>
                        <td class="label">Текст письма:</td>
                        <td><textarea name="mess"></textarea><br><br></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input class="btn-sub" type="submit" name="submit" value="Отправить"></td>
                    </tr>
                    </tbody></table>

                <input type="hidden" name="formid" value="form1"></form>
        </div>
        <div id="flash-msg-note" style="display: none;"></div>
    </div>
</div>

<div class="content">
    <div class="left-bg">
        <div class="head-left"></div>
        <div class="footer-left"></div>
    </div>
    <div class="right-bg"></div>

    <div class="head">

        <a href="/">
            <div class="logo"></div>
        </a>

        <div class="menu">
            <a href="/about">
                <div class="menu-item">
                    <div class="button-label <?= K_Url::get()->expPath[0] == 'about' ? 'active' : ''?>">
                        <div class="menu-about-img"></div>
                        <span>О компании</span>
                    </div>
                </div>
            </a>

            <a href="/contacts">
                <div class="menu-item">

                    <div class="button-label <?= K_Url::get()->expPath[0] == 'contacts' ? 'active' : ''?>">
                        <div class="menu-contacts-img"></div>
                        <span>Контакты</span>
                    </div>
                </div>
            </a>

            <a href="/service">
                <div class="menu-item">

                    <div class="button-label <?= K_Url::get()->expPath[0] == 'service' ? 'active' : ''?>">
                        <div class="menu-service-img"></div>
                        <span>Услуги</span>
                    </div>
                </div>
            </a>

            <!--                <div class="enter">-->
            <!--                    <a href="#">-->
            <!--                        <div class="menu-item">-->
            <!--                            <div class="button-label button-label-reg --><?//= K_Url::get()->expPath[0] == 'enter' ? 'active' : ''?><!--"><span>Вход</span></div>-->
            <!--                        </div>-->
            <!--                    </a>-->
            <!--                    <a href="#">-->
            <!--                        <div class="menu-item">-->
            <!--                            <div class="button-label button-label-reg --><?//= K_Url::get()->expPath[0] == 'registration' ? 'active' : ''?><!--"><span>Регистрация</span></div>-->
            <!--                        </div>-->
            <!--                    </a>-->
            <!--                </div>-->
        </div>
        <div class="clear"></div>
    </div>

    <div id="top-slider"></div>

    <div class="search">
        <div class="search-img">
            <div class="search-map-img">
                <p>Поиск</p>
            </div>
        </div>

        <div class="search-form">
            <form action="/resultsearch" method="post" id="search-form">
                <div class="block">
                    <div class="label">Страна:</div>
                    <div class="field">
                        <select id="country" name="country">
                            <option value="">Страна</option>
                            <?php $country = K_TreeQuery::crt('/allcountry/')->type(array('country'))->go();
                            foreach ($country as $v) {?>
                                <option treeid="<?= $v['tree_id'] ?>" value="<?= $v['tree_id'] ?>" data-name="<?= $v['tree_name'] ?>"><?= $v['name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="label">Регион:</div>
                    <div class="field">
                        <select id="region" disabled="disabled" name="region">
                            <option value="">Регион</option>
                        </select>
                    </div>

                    <div class="label">Город:</div>
                    <div class="field">
                        <select id="city" disabled="disabled" name="city">
                            <option value="">Город</option>
                        </select>
                    </div>

                    <div class="label">Тип:</div>
                    <div class="field">
                        <select name="type">
                            <option value="">Тип</option>
                            <?php $country = K_TreeQuery::crt('/type/')->type(array('typejk'))->go();
                            foreach ($country as $v) {?>
                                <option treeid="<?= $v['tree_id'] ?>"><?= $v['name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="block">
                    <div class="label">Рынок:</div>
                    <div class="field">
                        <select name="market">
                            <option value="">Рынок</option>
                            <?php
                            $market = K_Q::data('SELECT * FROM market');
                            foreach ($market as $v) {?>
                                <option value="<?= $v['id'] ?>"><?= $v['name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="label">Комн.:</div>
                    <div class="field">
                        <select name="rooms">
                            <option value="">Кол-во ком.</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">>5</option>
                        </select>
                    </div>

                    <div class="label">Площ.:</div>
                    <div class="field">
                        <input type="text" placeholder="Площадь до" name="sq">
                    </div>

                    <div class="label">Сост.:</div>
                    <div class="field">
                        <select name="state">
                            <option value="">Состояние</option>
                            <?php
                            $country = K_Q::data('SELECT * FROM state');
                            foreach ($country as $v) {?>
                                <option value="<?= $v['id'] ?>"><?= $v['name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="block-last">
                    <span>ID</span>
                    <input class="field-id" type="text" name="id">

                    <span>от</span>
                    <input class="field-price" type="text" name="price_from">

                    <span class="label-price">Цена</span>

                    <span>до</span>
                    <input class="field-price" type="text" name="price_to">
                </div>
            </form>
        </div>

        <a href="javascript:false">
            <div class="search-map-btn">
                <div class="search-text">На карте</div>
                <div class="search-map"></div>
                <div class="clear"></div>
            </div>
        </a>

        <a href="#"  onclick="document.getElementById('search-form').submit(); return false;">
            <div class="search-btn">
                <div class="search-text">Найти</div>
                <div class="find"></div>
                <div class="clear"></div>
            </div>
        </a>
    </div>

    <div class="clear"></div>

    <div class="left-part">
        <a href="/favorite">
            <div class="favorites">
                <div class="favorites-img">
                    <span id="count-fav"></span>
                </div>

                <div class="fav-label">
                    <p class="fav-title">Избранное</p>
                </div>
            </div>
        </a>

        <a href="javascript:false" onclick="show('block')">
            <div class="favorites contacts">
                <div class="contact-img"></div>

                <div class="fav-label">
                    <p class="fav-title">Контакты</p>
                </div>
            </div>
        </a>

        <?php if ($this->content['left']) { ?>
            <?php for ($i = 0; $i < sizeof($this->content['left']); $i++) { ?>
                <?=$this->content['left'][$i]?>
            <?php } ?>
        <?php } ?>

        <div class="main-part">
            <div class="clear"></div>

            <?php if ($this->content['middle']) { ?>
                <?php for ($i = 0; $i < sizeof($this->content['middle']); $i++) { ?>
                    <?=$this->content['middle'][$i]?>
                <?php } ?>
            <?php } ?>

            <!--Конец мейна-->
        </div>
        <div class="clear"></div>
        <div class="container-map">
            <div class="top-part">
                ПОИСК ПО КАРТЕ
            </div>

            <div id="map"></div>

            <div class="country-list">
                <div class="country-items">
                    <a href="javascript:false">
                        <div class="reset">
                            Сбросить
                        </div>
                    </a>
                    <?php
                    $country = K_TreeQuery::crt('/allcountry/')->type(array('country'))->go();
                    foreach ($country as $v) {
                        ?>
                        <a href="javascript:false">
                            <div class="country-item" data-country="<?= $v['tree_name']?>"
                                 data-id="<?= $v['tree_id']?>"
                                 data-idobj="<?= $v['idobj']?>">
                                <img src="/upload/<?= $v['flag'] ?>" width="40" height="25"><br>
                                <?= $v['name']?>
                            </div>
                        </a>

                    <?php } ?>
                    <div class="clear"></div>
                </div>


                <div class="city-items">

                </div>
            </div>

            <div class="recommended">

            </div>
        </div>

        <div class="main-head">
            <?= $this->settings['mainhead']?>
        </div>
        <div class="main-text">
            <?= $this->settings['maintext']?>
        </div>

        <br>
        <br>
        <br>

        <script type="text/javascript" src="/usr/js/jquery.form.js"></script>

        <script src="/usr/js/jquery.catslider.js"></script>

        <script type="text/javascript" src="/usr/js/menu.js"></script>
        <script type="text/javascript" src="/usr/js/main.js"></script>
        <script type="text/javascript" src="/usr/js/misc.js"></script>

        <script type="text/javascript" src="/usr/js/slides.js"></script>
        <script type="text/javascript" src="/usr/js/favorite.js"></script>

        <script type="text/javascript"
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgHkEihEPahT0h0EisUC3vsZv2cMnu5iU&sensor=false">
        </script>
        <script type="text/javascript" src="/usr/js/map.js"></script>


</body>
</html>