<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Админка - Div-studio</title>

<link href="/adm/css/main_frame.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css' />

<!-- libraries -->
<script src="/adm/js/jquery-1.7.2.min.js" type="text/javascript"></script>

<script type="text/javascript" src="/adm/js/spinner/jquery.mousewheel.js"></script>
<script type="text/javascript" src="/adm/js/spinner/ui.spinner.js"></script>

<script type="text/javascript" src="/adm/js/jquery-ui.min.js"></script> 

<script type="text/javascript" src="/adm/js/fileManager/elfinder.min.js"></script>

<script type="text/javascript" src="/adm/js/dataTables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/adm/js/dataTables/colResizable.min.js"></script>

<script type="text/javascript" src="/adm/js/forms/forms.js"></script>
<script type="text/javascript" src="/adm/js/forms/autogrowtextarea.js"></script>
<script type="text/javascript" src="/adm/js/forms/autotab.js"></script>
<script type="text/javascript" src="/adm/js/forms/jquery.validationEngine-en.js"></script>
<script type="text/javascript" src="/adm/js/forms/jquery.validationEngine.js"></script>

<script type="text/javascript" src="/adm/js/colorPicker/colorpicker.js"></script>

<script type="text/javascript" src="/adm/js/uploader/plupload.js"></script>
<script type="text/javascript" src="/adm/js/uploader/plupload.html5.js"></script>
<script type="text/javascript" src="/adm/js/uploader/plupload.html4.js"></script>
<script type="text/javascript" src="/adm/js/uploader/jquery.plupload.queue.js"></script>

<script type="text/javascript" src="/adm/js/ui/progress.js"></script>
<script type="text/javascript" src="/adm/js/ui/jquery.jgrowl.js"></script>
<script type="text/javascript" src="/adm/js/ui/jquery.tipsy.js"></script>
<script type="text/javascript" src="/adm/js/ui/jquery.alerts.js"></script>

<script type="text/javascript" src="/adm/js/jBreadCrumb.1.1.js"></script>
<script type="text/javascript" src="/adm/js/cal.min.js"></script>
<script type="text/javascript" src="/adm/js/jquery.collapsible.min.js"></script>
<script type="text/javascript" src="/adm/js/jquery.ToTop.js"></script>
<script type="text/javascript" src="/adm/js/jquery.listnav.js"></script>
<script type="text/javascript" src="/adm/js/jquery.sourcerer.js"></script>

<script type="text/javascript" src="/adm/js/jquery.form.js"></script>
<script type="text/javascript" src="/adm/js/tree/jquery.cookie.js" ></script>
<script type="text/javascript" src="/adm/js/tree/jquery.hotkeys.js"></script>

<script type="text/javascript" src="/adm/js/tree/jquery.jstree.js"></script>
<link href="/adm/js/tree/jqtree.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/adm/js/jquery.waterfall.js"></script>

<script type="text/javascript" src="/adm/js/jquery.formbuilder.js"></script>
<script type="text/javascript" src="/adm/js/redactor/redactor.js"></script>
<script type="text/javascript" src="/adm/js/jquery.ajaxleaf.js"></script>

<!-- client -->
<script type="text/javascript" src="/adm/js/misc.js"></script>
<script type="text/javascript" src="/adm/js/custom.js"></script>
<script type="text/javascript" src="/adm/js/main.js"></script>

<link href="/adm/js/redactor/css/redactor.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" media="screen" href="/adm/css/jquery.formbuilder.css"/>
		
</head>

<body> 

<!-- Content wrapper -->
<div class="wrapper">
	   <!-- Content -->
		<div class="content">
			<div class="widget tabsRight b-main-tabs">
				<div class="head"><h5 class="iFrames">Управление сайтом</h5></div>       
				<ul class="tabs" id="ajax_load_place_tabs">
         	    </ul>
				<div class="tab_container" id="ajax_load_place_tab_container">
						<?=$this->call->html(array(
                                              'module'     => 'admin',
                                              'controller' => 'gui',
                                              'action'     => 'load' ,
                                              'params'     => array('key' =>$this->key,'activeTab'=>'edit','needTabs'=>array('edit','node','comments','management'))
                                              ))?>
				</div>	
				<div class="fix"></div>	 
			</div>
		</div>
       
    <div class="fix"></div>
</div>

 <script type="text/javascript">
          $(function() {
 		  $("ul.tabs li:last").click();
           })
 </script>
</body>
</html>