<div class="presentation">
    <div class="item">
        <ul class="bxslider">
        <?php foreach($this->slider1 as $v){?>

            <li>
                <div class="item-name"><?= $v['name_build']?></div>
                <a href="<?= $v['tree_name']?>">
                    <img src="/upload/<?= $v['image'] ?>" alt="">
                </a>
                <div class="text">
                    <?= $v['text'] ?>
                </div>
                <p><?= $v['price']?></p>
            </li>
            <?php }?>
        </ul>
    </div>

    <div class="item middle">
        <ul class="bxslider">
            <?php foreach($this->slider2 as $v){?>
                <li>
                    <div class="item-name"><?= $v['name_build']?></div>
                    <a href="<?= $v['tree_name']?>">
                        <img src="/upload/<?= $v['image'] ?>" alt="">
                    </a>
                    <div class="text">
                        <?= $v['text'] ?>
                    </div>
                    <p><?= $v['price']?></p>
                </li>
            <?php }?>
        </ul>
    </div>

    <div class="item">
        <ul class="bxslider">
            <?php foreach($this->slider3 as $v){?>
                <li>
                    <div class="item-name"><?= $v['name_build']?></div>
                    <a href="<?= $v['tree_name']?>">
                        <img src="/upload/<?= $v['image'] ?>" alt="">
                    </a>
                    <div class="text">
                        <?= $v['text'] ?>
                    </div>
                    <p><?= $v['price']?></p>
                </li>
            <?php }?>
        </ul>
    </div>
</div>