<div style="margin-top: 8px;" class="table" id="services_table_wrapper">
	<div class="head">
		<h5 class="iFrames">
		    <?=$this->crudTitle?>
		</h5>
	</div>
	<div class="dataTables_wrapper" id="services_crud_wrapper">
        	
			<div class="dataTables_filter" id="acl-users_filter">
                          <a class="drop_filtres" onfocus="this.blur();" title="Сбросить фильтры" href="javascript:;"></a>
                          <span class="srchbutton b-button greyishBtn add_node_button"> Поиск </span>
            </div>
  			
		<table cellspacing="0" cellpadding="0" border="0" class="display">
			<thead>
				<tr>
                     <th class="ui-state-default" rowspan="1" colspan="1" style="width:25px;">
<div class="DataTables_sort_wrapper">ID<br/>
<input type="text" name="id" <?=isset($_GET['id'])? 'value="'.strip_tags(htmlspecialchars($_GET["id"])).'"' : ""?>  id="services_id" style="width:25px;" class="services-field" />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Дата добавления<br/>
от<input  type="text" name="start-date" id="start-services_date" value="" style="width:60px;" class="services-field datepicker"  /><br/>
до<input  type="text" name="stop-date" id="stop-services_date" value="" style="width:60px;" class="services-field datepicker"  />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:100px;">
<div class="DataTables_sort_wrapper">Пользователь<br/>
<select type="text" name="user" id="services_user" style="width:100px;"  class="services-field"  >
<?=K_jformhelper::options($this->selects->user, isset($_GET['user'])? strip_tags(htmlspecialchars($_GET["user"])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Раздел<br/>
<select type="text" name="category" id="services_category" style="width:80px;"  class="services-field"  >
<?=K_jformhelper::options($this->selects->category, isset($_GET['category'])? strip_tags(htmlspecialchars($_GET["category"])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Область<br/>
<select type="text" name="region" id="services_region" style="width:80px;"  class="services-field"  >
<?=K_jformhelper::options($this->selects->region, isset($_GET['region'])? strip_tags(htmlspecialchars($_GET["region"])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Лого<br/>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:25px;">
<div class="DataTables_sort_wrapper">Утв..<br/>
<input type="text" name="moderation" <?=isset($_GET['moderation'])? 'value="'.strip_tags(htmlspecialchars($_GET["moderation"])).'"' : ""?>  id="services_moderation" style="width:25px;" class="services-field" />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:50px;">
<div class="DataTables_sort_wrapper">Заголовок.<br/>
<input type="text" name="title" <?=isset($_GET['title'])? 'value="'.strip_tags(htmlspecialchars($_GET["title"])).'"' : ""?>  id="services_title" style="width:50px;" class="services-field" />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:50px;">
<div class="DataTables_sort_wrapper">Сайт<br/>
<input type="text" name="site" <?=isset($_GET['site'])? 'value="'.strip_tags(htmlspecialchars($_GET["site"])).'"' : ""?>  id="services_site" style="width:50px;" class="services-field" />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:150px;">
<div class="DataTables_sort_wrapper">Текст<br/>
<input type="text" name="text" <?=isset($_GET['text'])? 'value="'.strip_tags(htmlspecialchars($_GET["text"])).'"' : ""?>  id="services_text" style="width:150px;" class="services-field" />
</div>
</th>

                     
                    <th class="ui-state-default" rowspan="1" colspan="1" >
    		             <div class="DataTables_sort_wrapper">Управление</div>
                    </th>
            	</tr>
			</thead>
			<tbody>
	       	</tbody>
		</table>
		<div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
			<div id="acl-users_length" class="dataTables_length">
				<label>
					Элементов на страницу:
					<select name="acl-users_length" class="on-page-count" size="1">
						<option value="5">
							5
						</option>
						<option value="10" selected="selected">
							10
						</option>
						<option value="25">
							25
						</option>
						<option value="50">
							50
						</option>
						<option value="100">
							100
						</option>
					</select>
				</label>
			</div>
			<div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="acl-users_paginate">
				<span class="toFirst ui-corner-tl ui-corner-bl fg-button ui-button ui-state-disabled" id="acl-users_first">
					Первая
				</span>
				<span class="previous fg-button ui-button ui-state-disabled" id="acl-users_previous">
					Предыдущая
				</span>
				<span>
					<span class="fg-button ui-button ui-state-disabled">
						1
					</span>
				</span>
				<span class="next fg-button ui-button ui-state-disabled" id="acl-users_next">
					Следующая
				</span>
				<span class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-disabled" id="acl-users_last">
					Последняя
				</span>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

$(function(){
    
   $('#services_table_wrapper').ajaxLeaf({
    
			loadUrl:'/admin/services/load',
			itemsContainer: '#services_crud_wrapper',
            collectInfo:function(wrap){
                
                     var addInfoArray = [];
                
                     wrap.find('.services-field').each(function(){
                        
                          addInfoArray.push($(this).attr('name')+'='+$(this).val());
                       
                     });
                  
                     addInfo = addInfoArray.join('&');
                         
               	     return addInfo;
                     
			},
                 
            dropFiltres:function(wrap){
                
                     wrap.find('.services-field').each(function(){
                        
                         if($(this).tagName.toLowerCase()=="select"){
                            
                            $(this).find('options').attr('selected', false);
                          
                         }else{
                            
                            $(this).val('');
                            
                         }
                       
                     });
                      
            },    
                 
            dropFiltresButtonInd: '.drop_filtres',   
            srchButtonInd: '.srchbutton',
   			"renderItems": function(items) {
    				var itemsHtml = [];
    				$.each(items, function(id, v) {
    				itemsHtml.push('<tr class="services_row" id="services-row-' + v.id + '" rel="' + v.idname + '" ><td>' + v.id + '</td><td>' + v.date + '</td><td>' + v.user + '</td><td>' + v.category + '</td><td>' + v.region + '</td><td>' + v.logo + '</td><td>' + v.moderation + '</td><td>' + v.title + '</td><td>' + v.site + '</td><td>' + v.text + '</td><td><a href="javascript:void(0);" data-id="' + v.id + ' "class="crud-edit"></a><a title="Удалить запись" onclick="deleteServ(' + v.id + ')" data-id="' + v.id + '" class="crud-delete"></a></td></tr>');
                    });
                    
    				return itemsHtml;
            }
   }); 

   $('#services_crud_wrapper').on('click', '.crud-edit', function(){
            
            var id = $(this).data('id');
            
            $.get('/admin/services/edit','id='+id, function(data){
                  flyboxOpen(900+44,700, 'Управление', '<div style="padding:0 10px;width:900px;height:700px;overflow-x:auto">'+data+'</div>');
            },'html');
                    
   });
     
  /*
  $("#tree_title").syncTranslit({
    destination: "tree_name",
    urlSeparator: "-"
  });*/
  
});

</script>