<div class="fix">
</div>

<a class="btnIconLeft mr10 mt5 mb10 flr" href="javascript:;" onclick="addRole()" title="Новая роль">
<img class="icon" src="/adm/img/icons/dark/add.png" alt="Новый платёж"/>
<span onclick="editTrasaction('add')">Новый платёж</span>
</a>
<div class="fix">
</div>

<div style="margin-top: 8px;" class="table" id="transactions-table-wrapper">
	<div class="head">
		<h5 class="iFrames">
			История платежей
		</h5>
	</div>
    
    
	<div class="dataTables_wrapper" id="acl-users_wrapper">
		<div class="">
			<div class="dataTables_filter" id="acl-users_filter">
            <a class="drop_filtres" onfocus="this.blur();" title="Сбросить фильтры" href="javascript:;"></a>
				<label>
					Период с 
					<input id="reg-start" type="text" style="width: 100px;" class="datepickerl"/>
                </label>
                <label>
				    по
                    <input id="reg-stop" type="text"  style="width: 100px;" class="datepickerl"/>
       	       	</label>
                Статус
                <select id="status-type" style="width: 100px;">
                   <option value="">Любой</option>
                   <option value="confirmed">Подтвержден</option>
                   <option value="wait-confirmed">Ожидает подтверждения</option>
                   <option value="failure">Отказ</option>
                </select>
                Клиент 
                   	<input id="client" type="text" style="width: 120px;"/>   
                   <span class="srchbutton b-button greyishBtn add_node_button">
                Поиск
				  </span>
                  
                  
  			</div>
		</div>
		<table cellspacing="0" cellpadding="0" border="0" class="display" id="acl-users">
			<thead>
				<tr>
                    <th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
    						<div class="DataTables_sort_wrapper">
    					    Организация
    							<span class="DataTables_sort_icon">
    							</span>
    						</div>
    			    </th>
                	<th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
						<div class="DataTables_sort_wrapper">
					    	Плательщик
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
						<div class="DataTables_sort_wrapper">
							Дата
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
						<div class="DataTables_sort_wrapper">
							Метод оплаты
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
    	           <th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
						<div class="DataTables_sort_wrapper">
							Сумма
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
                    
					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 183px;">
						<div class="DataTables_sort_wrapper">
						    Статус
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
			       <th class="ui-state-default" rowspan="1" colspan="1" style="width: 144px;">
						<div class="DataTables_sort_wrapper">
					    	Комментарий
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
                     <th class="ui-state-default" rowspan="1" colspan="1" style="width: 144px;">
						<div class="DataTables_sort_wrapper">
					    	Управление
							<span class="DataTables_sort_icon">
							</span>
						</div>
					</th>
             		</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
		<div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
			<div id="acl-users_length" class="dataTables_length">
				<label>
					Элементов на страницу:
					<select name="acl-users_length" class="on-page-count" size="1">
						<option value="5" selected="selected">
							5
						</option>
						<option value="10" selected="selected">
							10
						</option>
						<option value="25">
							25
						</option>
						<option value="50">
							50
						</option>
						<option value="100">
							100
						</option>
					</select>
				</label>
			</div>
			<div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="acl-users_paginate">
				<span class="toFirst ui-corner-tl ui-corner-bl fg-button ui-button ui-state-disabled" id="acl-users_first">
					Первая
				</span>
				<span class="previous fg-button ui-button ui-state-disabled" id="acl-users_previous">
					Предыдущая
				</span>
				<span>
					<span class="fg-button ui-button ui-state-disabled">
						1
					</span>
				</span>
				<span class="next fg-button ui-button ui-state-disabled" id="acl-users_next">
					Следующая
				</span>
				<span class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-disabled" id="acl-users_last">
					Последняя
				</span>
			</div>
		</div>
	</div>
</div>
