<div class="content">

    <div class="block">
        <div class="p_cont">
            <h1>ЖК Альтаир</h1>
            <script type="text/javascript" src="//yandex.st/share/share.js"
                    charset="utf-8"></script>
            <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,friendfeed,moikrug,gplus,surfingbird"></div>

            <span class="intro"></span>
            <div class="clear"></div>

            <p><em><strong>Адрес:</strong></em>&nbsp; ул. Люстдорфская дорога, 55</p>
            <p><strong><em>Телефон:</em><span style="font-size: 120%;"> (048) 704-91-34</span></strong></p>
            <p><img style="float: left;" src="/upload/альтаир.jpg" alt="новострой Одессы Альтаир " width="250" height="178" /></p>
            <p><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;"><a>ЖК Альтаир</a> новый автономный комплекс от строительной компании &laquo;Будова&raquo;
                    на сегодняшний день является самым ярким проектом в Киевском районе.</span></p>
            <p><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">В </span><em><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">&nbsp;</span></em><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">состав комплекса входит 22 этажный 3-х секционный дом, с
                    подземным паркингоми гостевой охраняемой стоянкой.</span></p>
            <p><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">При строительстве монолитных домов применяются современные и
                    передовые технологии с использованием качественных экологически чистых
                    строительных материалов, что позволяет возводить дома повышенного комфорта.</span></p>
            <p><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">Пла</span><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">&nbsp;</span><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">нировки квартир продуманы до мелочей. Просторные кухни &ndash; мечта любой хозяйки.</span></p>
            <p><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">От внешнего воздействия Вас защищает энергосберегающие оконные
                    конструкции.</span></p>
            <p><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">Терри</span><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">&nbsp;</span><span style="font-size: 100%; font-family: arial, helvetica, sans-serif;">тория <span style="color: #000000;"><a href="sitemap">ЖК Альтаир</a></span>&nbsp;будет благоустроена. Предусмотрено озеленение, детские площадки, зоны отдыха, что позволяет Вам наслаждаться
                    тишиной и уютом вдали от городского шума.</span></p>
            <h2 style="text-align: center;"><span style="font-size: 100%;"><strong><em>План типового этажа</em></strong></span></h2>
            <p><img src="/upload/Альтаирпл.jpg" alt="План этажа ЖК Альтаир" width="800" height="496" /></p>
            <p><img style="line-height: 1.5;" src="/upload/2 секция Альтаир.jpg" alt="" width="800" height="487" /></p>
            <h2><strong style="line-height: 1.5;"><em>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Срок сдачи 4 квартал 2014 года</em></strong></h2>
            <p><strong style="line-height: 1.5;"><em><br /></em></strong></p>
            <h2 style="text-align: center;"><span style="color: #000000; font-family: tahoma, arial, helvetica, sans-serif;"><strong><em>Планировки 1-комнатных квартир :&nbsp;</em></strong></span><strong style="color: #000000; font-size: 120%; line-height: 1.5;"><em><span style="white-space: pre;">	<em>&nbsp;</em></span></em></strong></h2>
            <p><strong style="color: #000000; font-size: 120%; line-height: 1.5;"><em><span style="white-space: pre;"><em><br /></em></span></em></strong></p>
            <p><img style="float: left;" src="/upload/35,4 m2(1).JPG" alt="" width="300" height="262" /><em>&nbsp;<span style="white-space: pre;">	           	</span></em><em style="line-height: 1.5;"><span style="white-space: pre;"><img src="/upload/Planirivki/43,2 m2.JPG" alt="однокомнатная квартира в новострое" width="220" height="262" />			</span></em></p>
            <p><em style="line-height: 1.5;"><span style="white-space: pre;"><br /></span></em></p>
            <h2 style="text-align: center;"><span style="color: #000000;"><strong><em>Планировки 2-комнатных квартир :&nbsp;</em></strong></span></h2>
            <p><strong style="color: #111111; font-size: 1.5em; letter-spacing: 1px; line-height: 1.5;"><em><em><strong><img style="vertical-align: text-bottom;" src="/upload/Planirivki/63,7 m2.jpg" alt="2 комнатная квартира планировка" width="300" height="244" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></em></em></strong><img style="line-height: 1.5;" src="upload/Planirivki/70,3 m2.jpg" alt="планировка двухкомнатной квартиры Альтаир" width="215" height="400" /></p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h2 style="text-align: center;"><span><strong><em>Планировки 3-комнатных квартир :&nbsp;</em></strong></span></h2>
            <p>&nbsp;</p>
            <p><span><strong><em><img style="display: block; margin-left: auto; margin-right: auto;" src="/upload/Planirivki/3к_88 кв.м_Альтаир(1).jpg" alt="" width="750" height="596" /><br /></em></strong></span></p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <div>
                <p>&nbsp;</p>
                <p><span style="color: #000000;"><strong><span style="font-size: 320%;">&nbsp; </span></strong></span></p>
                <h1 class="tit justifyright"><span style="line-height: 1.5; font-size: 180%;">&nbsp;<span style="white-space: pre;">		 </span>+38 048 704 91 34</span></h1>
                <h1><em style="line-height: 1.5;"><span style="white-space: pre;">              </span></em></h1>
            </div>
        </div>
    </div>
    <div class="kran_cont"></div>
</div>