
<div id="login">
 <div id="flash-msg-nNote"  class="nNote hideit" style="display:none">
    <p></p>
</div>  

<?php

 if($this->error_msg): ?>

<script type="text/javascript">    
 nNoteShow('#flash-msg-nNote','nFailure','<?=$this->error_msg?>');
</script>
   
<?php endif;?>
<div class="logo" style="text-align:center ;" >

<img  src="/adm/img/logo.png"/>

</div>
    <h1>Вход</h1>
      <form action=""  method="post" enctype="multipart/form-data" id="x_form_create">
            <fieldset id="inputs">  
                <input id="username" type="text" name="login" placeholder="Логин" autofocus required>  
                <input id="password" type="password" name="password" placeholder="Пароль" required>  
            </fieldset>  
            
            <fieldset id="actions">  
                <input name="btnauth" type="submit" id="submit" class="b-button greyishBtn submitForm" value="Войти">  
            </fieldset>
      </form>
</div>