<div class="content">
    <div class="p_cont">
        <h2>ЖК Радужный</h2>
    </div>
    <p style="font-size: 16px;"><span style="color: #ffffff;"><img style="float: left; margin-left: 10px; margin-right: 10px;" src="/upload/raduj.jpg" alt="ЖК Радужный новостройка Одесса" width="400" height="266"></span></p>
    <p style="font-size: 90%; color: #ffffff;"><a href="http://novidom.od.ua/">ЖК Радужный</a> - новый жилой комплекс, расположенный в одном из наиболее быстро
        развивающихся микрорайонов Одессы, состоящий из 11 введённых в
        эксплуатацию и 7 строящихся домов.</p>
    <p style="font-size: 90%; color: #ffffff;">Высокие темпы строительства,
        применение новейших технологий, своевременное введение объектов в
        эксплуатацию, в сочетании с качественным строительством и разнообразием
        планировок даёт возможность при покупке квартиры удовлетворить самые
        высокие требования и изысканный вкус.</p>
    <p>&nbsp;</p>
    <p style="font-size: 16px;">&nbsp;</p>
    <p style="font-size: 16px;">&nbsp;</p>
    <p style="font-size: 16px;">&nbsp;</p>
    <p style="font-size: 16px;">&nbsp;</p>
    <p style="font-size: 16px;"><span style="color: #ffffff;">Планировки:&nbsp;</span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;"><img src="/upload/rad_1.png" alt="планировка квартир жк радужный" width="606" height="242">&nbsp;</span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;">1-но комнатные квартиры:</span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;"><img src="/upload/rad_2.jpg" alt="схема однокомнатной квартиры жк радужный" width="526" height="675">&nbsp;</span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;">2-х комнатные квартиры:</span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;"><img src="/upload/rad_3.png" alt="двухкомнатные квартиры новострой радужный" width="606" height="1272"></span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;">3-х комнатные квартиры:</span></p>
    <p style="font-size: 16px;"><span style="color: #ffffff;"><img src="/upload/1.jpg" alt="трёхкомнатная квартира новостройка в одессе" width="941" height="789">&nbsp;</span></p>
</div>
<div class="clear"></div>