<div class="bottom-part">
    <div class="top-part"></div>
    <div class="down-part"></div>
    <div class="bottom-down-img">
        <span>Архив новостей</span>
    </div>

    <div class="bottom-left-part">
        <div class="bottom-news-head">
            <span>Новости зарубежной недвижимости</span>
        </div>
            <?php foreach ($this->newsOut as $news) { ?>
                <div class="bottom-news">
                    <img src="/upload/<?= $news['image'] ?>">
                    <div class="bottom-news-text">
                        <p><?= $news['text'] ?></p>
                    </div>
                    <p class="news-date"><?= date("j-m-Y", strtotime($news['date'])) ?></p>
                    <div class="clear"></div>
                </div>
            <?php }?>
    </div>

    <div class="bottom-right-part">
        <div class="bottom-news-head">
            <span>Новости компании</span>
        </div>
            <?php foreach ($this->newsIn as $news) { ?>
                <div class="bottom-news">
                    <img src="/upload/<?= $news['image'] ?>">
                    <div class="bottom-news-text">
                        <p><?= $news['text'] ?></p>
                    </div>
                    <p class="news-date"><?= date("j-m-Y", strtotime($news['date'])) ?></p>
                    <div class="clear"></div>
                </div>
            <?php }?>
    </div>

    <div class="clear"></div>
</div>