<div class="bottom-part">
    <div class="top-part"></div>
    <div class="down-part"></div>
    <div class="bottom-down-img">
        <span>Архив новостей</span>
    </div>

    <div class="bottom-left-part">
        <div class="bottom-news-head">
            <a href="/news-out">
                <span>Новости зарубежной недвижимости</span>
            </a>
        </div>
            <?php foreach ($this->newsz as $news) {?>

                <a href="<?= $news['tree_name'] ?>">
                    <div class="bottom-news">
                        <img src="/upload/<?= $news['image'] ?>">
                        <div class="bottom-news-text">
                            <p><?= $news['text'] ?></p>
                        </div>
                        <p class="news-date"><?= date("j-m-Y", strtotime($news['date'])) ?></p>
                        <div class="clear"></div>
                    </div>
                </a>
            <?php }?>
    </div>

    <div class="bottom-right-part">
        <div class="bottom-news-head">
            <a href="/news-in">
                <span>Новости компании</span>
            </a>
        </div>
            <?php foreach ($this->newsk as $news) { ?>
                <a href="<?= $news['tree_name'] ?>">
                    <div class="bottom-news">
                        <img src="/upload/<?= $news['image'] ?>">
                        <div class="bottom-news-text">
                            <p><?= $news['text'] ?></p>
                        </div>
                        <p class="news-date"><?= date("j-m-Y", strtotime($news['date'])) ?></p>
                        <div class="clear"></div>
                    </div>
                </a>
            <?php }?>
    </div>

    <div class="clear"></div>
