<div style="margin-top: 8px;" class="table" id="ads_table_wrapper">
	<div class="head">
		<h5 class="iFrames">
		    <?=$this->crudTitle?>
		</h5>
	</div>
	<div class="dataTables_wrapper" id="ads_crud_wrapper">
        	
			<div class="dataTables_filter" id="acl-users_filter">
                          <a class="drop_filtres" onfocus="this.blur();" title="Сбросить фильтры" href="javascript:;"></a>
                          <span class="srchbutton b-button greyishBtn add_node_button"> Поиск </span>
            </div>
  			
		<table cellspacing="0" cellpadding="0" border="0" class="display">
			<thead>
				<tr>
                     <th class="ui-state-default" rowspan="1" colspan="1" style="width:40px;">
<div class="DataTables_sort_wrapper">ID<br/>
<input type="text" name="id" id="ads_id" value="" style="width:40px;" class="ads-field" />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Дата добавления<br/>
от<input  type="text" name="start-date" id="start-ads_date" value="" style="width:60px;" class="ads-field datepicker"  /><br/>
до<input  type="text" name="stop-date" id="stop-ads_date" value="" style="width:60px;" class="ads-field datepicker"  />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Дата публикации<br/>
от<input  type="text" name="start-pub" id="start-ads_pub" value="" style="width:60px;" class="ads-field datepicker"  /><br/>
до<input  type="text" name="stop-pub" id="stop-ads_pub" value="" style="width:60px;" class="ads-field datepicker"  />
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:100px;">
<div class="DataTables_sort_wrapper">e-mail пользователя<br/>
<select type="text" name="user" id="ads_user" style="width:100px;"  class="ads-field"  >
<?=K_jformhelper::options($this->selects->user, isset($_GET['user'])? strip_tags(htmlspecialchars($_GET['user'])) : null)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:100px;">
<div class="DataTables_sort_wrapper">ФИО пользователя<br/>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Операция<br/>
<select type="text" name="type_transac" id="ads_type_transac" style="width:80px;"  class="ads-field"  >
<?=K_jformhelper::options($this->selects->type_transac)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Категория<br/>
<select type="text" name="category" id="ads_category" style="width:80px;"  class="ads-field"  >
<?=K_jformhelper::options($this->selects->category)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Раздел<br/>
<select type="text" name="type_propert" id="ads_type_propert" style="width:80px;"  class="ads-field"  >
<?=K_jformhelper::options($this->selects->type_propert)?></select>
</div>
</th>
<th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
<div class="DataTables_sort_wrapper">Область<br/>
<select type="text" name="region" id="ads_region" style="width:80px;"  class="ads-field"  >
<?=K_jformhelper::options($this->selects->region)?></select>
</div>
</th>

                     
                    <th class="ui-state-default" rowspan="1" colspan="1" >
    		             <div class="DataTables_sort_wrapper">Управление</div>
                    </th>
            	</tr>
			</thead>
			<tbody>
	       	</tbody>
		</table>
		<div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
			<div id="acl-users_length" class="dataTables_length">
				<label>
					Элементов на страницу:
					<select name="acl-users_length" class="on-page-count" size="1">
						<option value="5">
							5
						</option>
						<option value="10" selected="selected">
							10
						</option>
						<option value="25">
							25
						</option>
						<option value="50">
							50
						</option>
						<option value="100">
							100
						</option>
					</select>
				</label>
			</div>
			<div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="acl-users_paginate">
				<span class="toFirst ui-corner-tl ui-corner-bl fg-button ui-button ui-state-disabled" id="acl-users_first">
					Первая
				</span>
				<span class="previous fg-button ui-button ui-state-disabled" id="acl-users_previous">
					Предыдущая
				</span>
				<span>
					<span class="fg-button ui-button ui-state-disabled">
						1
					</span>
				</span>
				<span class="next fg-button ui-button ui-state-disabled" id="acl-users_next">
					Следующая
				</span>
				<span class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-disabled" id="acl-users_last">
					Последняя
				</span>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

$(function(){
    
   $('#ads_table_wrapper').ajaxLeaf({
    
			loadUrl:'/admin/ads/load',
			itemsContainer: '#ads_crud_wrapper',
            collectInfo:function(wrap){
                
                     var addInfoArray = [];
                
                     wrap.find('.ads-field').each(function(){
                        
                          addInfoArray.push($(this).attr('name')+'='+$(this).val());
                       
                     });
                  
                     addInfo = addInfoArray.join('&');
                         
               	     return addInfo;
                     
			},
                 
            dropFiltres:function(wrap){
                
                     wrap.find('.ads-field').each(function(){
                        
                         if($(this).tagName.toLowerCase()=="select"){
                            
                            $(this).find('options').attr('selected', false);
                          
                         }else{
                            
                            $(this).val('');
                            
                         }
                       
                     });
                      
            },    
                 
            dropFiltresButtonInd: '.drop_filtres',   
            srchButtonInd: '.srchbutton',
   			"renderItems": function(items) {
    				var itemsHtml = [];
    				$.each(items, function(id, v) {

    		      		itemsHtml.push('<tr class="ads_row" id="ads-row-' + v.id + '" rel="' + v.idname + '" ><td><a href="/ads-'+ v.id + '" target="_blank">'+ v.id + '</a></td><td>' + v.date + '</td><td>' + v.pub + '</td><td>' + v.user + '</td><td>' + v.name + ' ' + v.fam +'</td><td>' + v.type_transac + '</td><td>' + v.category + '</td><td>' + v.type_propert + '</td><td>' + v.region + '</td><td><a target="_blank" href="http://dom.pliz.info/add?r='+ v.id +'">Редактировать</a><a title="Удалить запись" onclick="deleteAd(' + v.id + ')" data-id="' + v.id + '" class="crud-delete"></a></td></tr>');

                    });
                    
    				return itemsHtml;
            }
   }); 

   $('#ads_crud_wrapper').on('click', '.crud-edit', function(){
            
            var id = $(this).data('id');
            
            $.get('/admin/ads/edit','id='+id, function(data){
                  flyboxOpen(900+44,700, 'Управление', '<div style="padding:0 10px;width:900px;height:700px;overflow-x:auto">'+data+'</div>');
            },'html');
                    
   });
     
  /*
  $("#tree_title").syncTranslit({
    destination: "tree_name",
    urlSeparator: "-"
  });*/
  
});

</script>