<div style="margin-top: 8px;" class="table">
            	<div class="head">
            		<h5 class="iFrames">
                    
                     <?=$this->item? "Редактирование записи":'Добавление запсии'?>
                     
            		</h5>
            	</div>
<form action="/admin/ads/save/id/<?=$this->item['id']?>" class="ajax-form" method="post">                
<table cellspacing="0" cellpadding="0" border="0" class="display edit-table" id="con-edit" >
            <thead>
				<tr>
               		<th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
						<div class="DataTables_sort_wrapper">
					    Характеристика
						</div>
					</th>
					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
						<div class="DataTables_sort_wrapper">
						Значение
						</div>
					</th>
		          
      			</tr>
		 	</thead>
  	<tbody>
      <a></a>
        
      <?if($this->item): ?>
      
		<tr>
			<td>
			ID
			</td>
			<td>
		       <?=htmlspecialchars(strip_tags($this->item['id']))?>
               <input type="hidden" name="id" value="<?=htmlspecialchars(strip_tags($this->item['id']))?>"/>
			</td>
		</tr>
        
      <?endif;?>
      
            
    
             
</tbody>

</table>

<input type="submit" value="<?=$this->item? "Обновить":'Создать'?>" id="add_button" class="b-button greyishBtn submitForm add_node_button"/>
<div style="display:none" class="nNote hideit" id="flash-msg-nNote">
	<p>
	</p>
</div>
</form>

</div>
        
   
        
