<div style="display:none" class="nNote hideit" id="flash-msg-nNote">
	<p>
	</p>
</div>
<div style="margin-top: 8px;" class="table">
            	<div class="head">
            		<h5 class="iFrames">
                      	Редактирование комментария 
            		</h5>
            	</div>
<form action="/admin/comments/save/id/<?=$this->commentRow['id']?>" class="ajax-form" method="post">                
<table cellspacing="0" cellpadding="0" border="0" class="display edit-table" id="con-edit" >
                <thead>
				<tr>
               		<th class="ui-state-default" rowspan="1" colspan="1" style="width: 120px;">
						<div class="DataTables_sort_wrapper">
					    Характеристика
						</div>
					</th>
					<th class="ui-state-default" rowspan="1" colspan="1" style="width: 129px;">
						<div class="DataTables_sort_wrapper">
						Значение
						</div>
					</th>
		          
      			</tr>
		 	</thead>
  	<tbody>
		<tr>
			<td>
			    Имя
			</td>
			<td>
				<input type="text" name="name"  value="<?=htmlspecialchars(strip_tags($this->commentRow['name']))?>"/>
			</td>
		</tr>
		<tr>
			<td>
			   Комментарий
			</td>
			<td>
               <textarea cols="80" rows="10" name="content"><?=htmlspecialchars(strip_tags($this->commentRow['content']))?></textarea>
			</td>
		</tr>
</tbody>
</table>
<input type="submit" value="Сохранить" id="add_button" class="b-button greyishBtn submitForm add_node_button"/>
</form>
</div>
        
        
        
