<div style="margin-top: 8px;" class="table" id="import_table_wrapper">
	<div class="head">
        <h5 class="iFrames">
            <?=$this->crudTitle?>
        </h5>
    </div>
    <div class="dataTables_wrapper" id="import_crud_wrapper">
        	
        <div class="dataTables_filter" id="acl-users_filter">
            <a class="drop_filtres" onfocus="this.blur();" title="Сбросить фильтры" href="javascript:;"></a>
            <span class="srchbutton b-button greyishBtn add_node_button"> Поиск </span>
        </div>
  			
        <table cellspacing="0" cellpadding="0" border="0" class="display">
            <thead>
            <tr>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:30px;">
                    <div class="DataTables_sort_wrapper">ID<br/>
                        <input type="text" name="id" <?=isset($_GET['id'])? 'value="'.strip_tags(htmlspecialchars($_GET["id"])).'"' : ""?>  id="import_id" style="width:30px;" class="import-field" />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Запускался<br/>
                        от<input  type="text" name="start-start_date" id="start-import_start_date" value="" style="width:60px;" class="import-field datepicker"  /><br/>
                        до<input  type="text" name="stop-start_date" id="stop-import_start_date" value="" style="width:60px;" class="import-field datepicker"  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">В файле импорта<br/>
                        от<input  type="text" name="start-infeed" id="start-import_infeed" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-infeed" id="stop-import_infeed" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Обработ.<br/>
                        от<input  type="text" name="start-processed" id="start-import_processed" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-processed" id="stop-import_processed" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Опубликован<br/>
                        от<input  type="text" name="start-publicated" id="start-import_publicated" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-publicated" id="stop-import_publicated" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Обновлен<br/>
                        от<input  type="text" name="start-updated" id="start-import_updated" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-updated" id="stop-import_updated" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Удален<br/>
                        от<input  type="text" name="start-deleted" id="start-import_deleted" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-deleted" id="stop-import_deleted" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Ошибок<br/>
                        от<input  type="text" name="start-errors" id="start-import_errors" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-errors" id="stop-import_errors" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Добавлен<br/>
                        от<input  type="text" name="start-add_date" id="start-import_add_date" value="" style="width:60px;" class="import-field datepicker"  /><br/>
                        до<input  type="text" name="stop-add_date" id="stop-import_add_date" value="" style="width:60px;" class="import-field datepicker"  />
                    </div>
                </th>
                <th class="ui-state-default" rowspan="1" colspan="1" style="width:80px;">
                    <div class="DataTables_sort_wrapper">Лимит<br/>
                        от<input  type="text" name="start-limit" id="start-import_limit" value="" style="width:60px;" class="import-field "  /><br/>
                        до<input  type="text" name="stop-limit" id="stop-import_limit" value="" style="width:59px;" class="import-field "  />
                    </div>
                </th>

                     
                <th class="ui-state-default" rowspan="1" colspan="1" >
                    <div class="DataTables_sort_wrapper">Управление</div>
                </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-bl ui-corner-br ui-helper-clearfix">
            <div id="acl-users_length" class="dataTables_length">
                <label>
                    Элементов на страницу:
                    <select name="acl-users_length" class="on-page-count" size="1">
                        <option value="5">
                            5
                        </option>
                        <option value="10" selected="selected">
                            10
                        </option>
                        <option value="25">
                            25
                        </option>
                        <option value="50">
                            50
                        </option>
                        <option value="100">
                            100
                        </option>
                    </select>
                </label>
            </div>
            <div class="dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers" id="acl-users_paginate">
                <span class="toFirst ui-corner-tl ui-corner-bl fg-button ui-button ui-state-disabled" id="acl-users_first">
                    Первая
                </span>
                <span class="previous fg-button ui-button ui-state-disabled" id="acl-users_previous">
                    Предыдущая
                </span>
                <span>
                    <span class="fg-button ui-button ui-state-disabled">
                        1
                    </span>
                </span>
                <span class="next fg-button ui-button ui-state-disabled" id="acl-users_next">
                    Следующая
                </span>
                <span class="last ui-corner-tr ui-corner-br fg-button ui-button ui-state-disabled" id="acl-users_last">
                    Последняя
                </span>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function(){
    
        $('#import_table_wrapper').ajaxLeaf({
    
            loadUrl:'/admin/import/load',
            itemsContainer: '#import_crud_wrapper',
            collectInfo:function(wrap){
                
                var addInfoArray = [];
                
                wrap.find('.import-field').each(function(){
                        
                    addInfoArray.push($(this).attr('name')+'='+$(this).val());
                       
                     });
                  
                     addInfo = addInfoArray.join('&');
                         
               	     return addInfo;
                     
			},
                 
            dropFiltres:function(wrap){
                
                     wrap.find('.import-field').each(function(){
                        
                         if($(this).tagName.toLowerCase()=="select"){
                            
                            $(this).find('options').attr('selected', false);
                          
                         }else{
                            
                            $(this).val('');
                            
                         }
                       
                     });
                      
            },    
                 
            dropFiltresButtonInd: '.drop_filtres',   
            srchButtonInd: '.srchbutton',
   			"renderItems": function(items) {
    				var itemsHtml = [];
    				$.each(items, function(id, v) {
    				itemsHtml.push('<tr class="import_row" id="import-row-' + v.id + '" rel="' + v.idname + '" ><td>' + v.id + '</td><td>' + v.start_date + '</td><td>' + v.infeed + '</td><td>' + v.processed + '</td><td>' + v.publicated + '</td><td>' + v.updated + '</td><td>' + v.deleted + '</td><td>' + v.errors + '</td><td>' + v.add_date + '</td><td>' + v.limit + '</td><td><a href="javascript:void(0);" data-id="' + v.id + ' "class="crud-edit"></a><a title="Удалить запись" href="javascript:void(0);" data-id="' + v.id + '" class="crud-delete"></a></td></tr>');
                    });
                    
    				return itemsHtml;
            }
   }); 

   $('#import_crud_wrapper').on('click', '.crud-edit', function(){
            
            var id = $(this).data('id');
            
            $.get('/admin/import/edit','id='+id, function(data){
                  flyboxOpen(900+44,700, 'Управление', '<div style="padding:0 10px;width:900px;height:700px;overflow-x:auto">'+data+'</div>');
            },'html');
                    
   });
     
   $('#import_crud_wrapper').on('click', '.crud-delete', function(){
            
        var id = $(this).data('id');
          
		
		if (confirm("Вы действительно хотите удалить эту запись?")) {
			
            $.post('/admin/import/remove',{id:id}, function(data){
                if(data.error){
				
				 	alert(data.msg);			 
				 
				}else{
				
					$('#<%crudName%>-row-'+data.id).remove();
				 
				}
				
            },'json');
        }
		
   });	 
	 
  /*
  $("#tree_title").syncTranslit({
    destination: "tree_name",
    urlSeparator: "-"
  });*/
  
});

</script>